### ISSUE TITLE
don't redo on deleting f""

### ISSUE THREAD

**Issue by bhakta0007** [mdebi/fstring-converter#1]
Say I started typing a string "blah {foo}", the extension instantly puts an f"...." which is cool

However, If I want to remove the f and do a backspace on it, the extension put back the f"" again.

Can you control this behavior by a setting - which by default does not retry if user removes the f""

**Comment by mdebi** [comment]
Hello. I'll explore if I can control not redoing addition of f in this case with a setting. Thank you for the suggestion.

One way to achieve this currently will be to use undo (instead of removing f) immediately after it adds as f. It will not add the f again.

**Comment by mdebi** [comment]
@bhakta0007, 

By default it should allow removing f added now and is controlled by the setting `fstring-converter.skipEvaluationPostManualDeletionOfF`. However another edit in the same line would add the f back as we have no way of maintaining the version. The f can still be removed.

Please try with v0.1.2 of the plugin and let me know if it solves your problem. Thank you.
