### ISSUE TITLE
Raw and unicode strings 

### ISSUE THREAD

**Issue by esauvisky** [mdebi/fstring-converter#14]
Strings starting with `r` or `u` aren't ignored, which is particularly troublesome with regexes, as curly braces are common:
`re.match(r'fo{2}')` will become `re.match(rf'fo{2}')`, thus breaking the match.

I fixed it by ignoring any strings that begin with `r` or `u`, both when adding as when removing the `f`, which also has the added bonus of providing a mechanism of forcing the extension to ignore certain strings by making them an unicode string.

**Comment by mdebi** [comment]
Hello, I like this part. Especially, with 'r' it is now a possible work around to force no addition of 'f'. Thanks for the PR. 

> which also has the added bonus of providing a mechanism of forcing the extension to ignore certain strings by making them an unicode string.

**Comment by mdebi** [comment]
Fixed by #18. Yet to be released.
