### ISSUE TITLE
incorrect f-string added

### ISSUE THREAD

**Issue by bhakta0007** [mdebi/fstring-converter#3]
I had this statement
cur.execute(f"delete from sites where name='{siteName}';")

While I was editing this, the plugin ended up doing this:

cur.execute(f"delete from sites where name=f'{siteName}';")

combined that with the behavior of it not able to revert the auto-added f-strings, it becomes painful to deal with this.. need to undo every change

**Comment by mdebi** [comment]
@bhakta0007 ,

Thank you for the feedback. With v0.1.2 the extension should allow removing f which would make this easier.

I'll check and address this bug.

**Comment by mdebi** [comment]
@bhakta0007 ,

The scenario reported by you should have been addressed in v1.0.0. Please review and reopen/create a new issue if the issue persists. Thank you for the feedback.
