### ISSUE TITLE
Incorrect `f` location when there is an escaped `'` in the string

### ISSUE THREAD

**Issue by timhughes** [mdebi/fstring-converter#8]
When a string has an escaped `'` you cannot put a `f` at the front and it insists on putting the `f` in the string. Try getting the following to have a `f `  at the front. 

```
'Something\'s f"{foo}"'
```

Switching the non-escaped `'` for `"` and you cannot get a `f` to appear at all

```
"Something's \"{secret_arn}\""
```

**Comment by mdebi** [comment]
Thank you @timhughes for the feedback. This should be fixed now with 1.0.2 version. Please reopen this issue if not working still.

**Comment by timhughes** [comment]
I can confirm it is working as expected  - thanks for the fix
